#define STEPS_PER_REVOLUTION_X 3200
#define STEPS_PER_REVOLUTION_Z 3200
#define STEPS_PER_REVOLUTION_E 3200
#define STEPS_PER_REVOLUTION_Y 6400

#define IDLER_TEETH_X 20
#define IDLER_TEETH_Y 20


#define BELT_PITCH_X (.2 * MM_PER_INCH)
#define BELT_PITCH_Y (.2 * MM_PER_INCH)

#define PITCH_OF_Z_ROD 1.25

// makergear extruder box
#define EXTRUDER_GEAR_RATIO 13.0

#define PINCH_WHEEL_DIAMETER 11.59

#define AXIS_STEPS_PER_UNIT_X (STEPS_PER_REVOLUTION_X / IDLER_TEETH_X / BELT_PITCH_X)

#define AXIS_STEPS_PER_UNIT_Y (STEPS_PER_REVOLUTION_Y / IDLER_TEETH_Y / BELT_PITCH_Y)

#define AXIS_STEPS_PER_UNIT_Z (STEPS_PER_REVOLUTION_Z / PITCH_OF_Z_ROD)

#define AXIS_STEPS_PER_UNIT_E (STEPS_PER_REVOLUTION_E * EXTRUDER_GEAR_RATIO / (PINCH_WHEEL_DIAMETER * PI))

#define DEFAULT_AXIS_STEPS_PER_UNIT {AXIS_STEPS_PER_UNIT_X, AXIS_STEPS_PER_UNIT_Y, AXIS_STEPS_PER_UNIT_Z, AXIS_STEPS_PER_UNIT_E}
